INSERT INTO products (product_name, product_category, price, image_url, is_favorite) VALUES 
    ('iPhone 14', 'Electronics', 999.99, 'https://example.com/iphone14.jpg', true),
    ('Galaxy S22', 'Electronics', 899.99, 'https://example.com/galaxys22.jpg', false),
    ('Sony WH-1000XM4', 'Electronics', 349.99, 'https://example.com/sonyheadphones.jpg', true),
    ('Dell XPS 13', 'Computers', 1199.99, 'https://example.com/dellxps13.jpg', false),
    ('MacBook Pro', 'Computers', 2499.99, 'https://example.com/macbookpro.jpg', true),
    ('Nike Air Max 270', 'Footwear', 149.99, 'https://example.com/airmax270.jpg', false),
    ('Adidas Ultraboost', 'Footwear', 179.99, 'https://example.com/ultraboost.jpg', true),
    ('North Face Jacket', 'Apparel', 199.99, 'https://example.com/northfacejacket.jpg', false),
    ('Jeans', 'Apparel', 79.99, 'https://example.com/levisjeans.jpg', true),
    ('Dyson V11 Vacuum', 'Home Appliances', 599.99, 'https://example.com/dysonv11.jpg', false),
    ('Instant Pot Duo', 'Home Appliances', 99.99, 'https://example.com/instantpot.jpg', true),
    ('KitchenAid Mixer', 'Kitchen', 399.99, 'https://example.com/kitchenaidmixer.jpg', false),
    ('Ninja Blender', 'Kitchen', 129.99, 'https://example.com/ninjablender.jpg', true),
    ('LG OLED TV', 'Electronics', 1799.99, 'https://example.com/lgoled.jpg', false),
    ('Sony PlayStation 5', 'Gaming', 499.99, 'https://example.com/ps5.jpg', true),
    ('Microsoft Xbox Series X', 'Gaming', 499.99, 'https://example.com/xboxseriesx.jpg', false),
    ('Nintendo Switch', 'Gaming', 299.99, 'https://example.com/switch.jpg', true),
    ('Canon EOS R6', 'Cameras', 2499.99, 'https://example.com/canoneosr6.jpg', false),
    ('GoPro HERO9', 'Cameras', 399.99, 'https://example.com/goprohero9.jpg', true),
    ('Fitbit Charge 4', 'Wearables', 149.99, 'https://example.com/fitbitcharge4.jpg', false);